# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run wishlister

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  schedule:
#    - cron: "13 6 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff poetry
        poetry install
    - name: Lint with Ruff
      run: |
        ruff check
      continue-on-error: true
    - name: Run script
      run: |
        poetry run python wishlister.py
